universe    = vanilla
executable  = runCondor_Data.sh

py_script = PbPb2023_D0BothAndDStar_MB_cfg_Step2MVA_condor_v1.py

arguments   = cmsRun $(py_script) $(inFName) $(idx) $(dataset)
transfer_input_files = $(py_script), myProxy

output      = /dev/null
error       = /dev/null
log         = /dev/null
+JobFlavour = "tomorrow"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

##### No Output
output = logs/job_$(idx).log
error = logs/job_$(idx).err
log = logs/job_$(idx).log
should_transfer_files   = YES

request_memory = 8 GB
request_cpus = 4
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el8:latest"

x509userproxy = myProxy
requirements = (OpSysAndVer =?= "AlmaLinux9")

queue inFName,idx,dataset from file_Data_HIPhysicsRawPrime13.list
